apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'producer'
        static_configs:
          - targets: ['producer-service:80']

      - job_name: 'consumer'
        static_configs:
          - targets: ['consumer-service:80']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter-service:9100']