version: '3.7'

services:
  kitchen-api:
    build:
      context: .
      dockerfile: FastTechFoods.Kitchen.API/Dockerfile
    container_name: kitchen-api
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
    networks:
      - default
      
  kitchen-worker:
    build:
      context: .
      dockerfile: FastTechFoods.Kitchen.Worker/Dockerfile
    container_name: kitchen-worker
    depends_on:
      - rabbitmq
    networks:
      - default

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - default

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    networks:
      - default
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # comunicação com apps
      - "15672:15672"     # dashboard do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - default

networks:
  default:
    external:
      name: fiap-hackaton-fasttechfoods_default

volumes:
  grafana-data:
