apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer
  type: NodePort
  ports:
    - name: http
      port: 80        
      targetPort: 8080
      nodePort: 31000 
